package com.moviebooking.integration;

import com.moviebooking.exception.PaymentException;
import com.razorpay.Order;
import com.razorpay.RazorpayClient;
import com.razorpay.RazorpayException;
import com.razorpay.Utils;
import org.json.JSONObject;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import java.nio.charset.StandardCharsets;
import java.util.Formatter;

/**
 * Service for integrating with Razorpay Payment Gateway.
 * 
 * Handles:
 * - Order creation
 * - Payment signature verification
 * - Webhook signature verification
 */
@Service
public class RazorpayService {

    private static final Logger logger = LoggerFactory.getLogger(RazorpayService.class);

    private final RazorpayClient razorpayClient;
    private final String webhookSecret;

    public RazorpayService(
            @Value("${razorpay.key.id}") String keyId,
            @Value("${razorpay.key.secret}") String keySecret,
            @Value("${razorpay.webhook.secret}") String webhookSecret) {
        
        try {
            this.razorpayClient = new RazorpayClient(keyId, keySecret);
            this.webhookSecret = webhookSecret;
            logger.info("RazorpayService initialized successfully");
        } catch (RazorpayException e) {
            logger.error("Failed to initialize RazorpayClient", e);
            throw new PaymentException("Failed to initialize payment gateway", e);
        }
    }

    /**
     * Create a Razorpay order.
     * 
     * @param amount Amount in paise (smallest currency unit)
     * @param currency Currency code (e.g., "INR")
     * @param receipt Receipt ID for tracking
     * @return Razorpay order ID
     */
    public String createOrder(Integer amount, String currency, String receipt) {
        logger.info("Creating Razorpay order: amount={}, currency={}, receipt={}", 
            amount, currency, receipt);

        try {
            JSONObject orderRequest = new JSONObject();
            orderRequest.put("amount", amount);
            orderRequest.put("currency", currency);
            orderRequest.put("receipt", receipt);
            orderRequest.put("payment_capture", 1); // Auto capture payment

            Order order = razorpayClient.orders.create(orderRequest);
            String orderId = order.get("id");
            
            logger.info("Razorpay order created: {}", orderId);
            return orderId;
            
        } catch (RazorpayException e) {
            logger.error("Failed to create Razorpay order", e);
            throw new PaymentException("Failed to create payment order: " + e.getMessage(), e);
        }
    }

    /**
     * Verify payment signature using Razorpay SDK.
     * 
     * The signature is generated by Razorpay using:
     * HMAC-SHA256(order_id + "|" + payment_id, key_secret)
     * 
     * @param orderId Razorpay order ID
     * @param paymentId Razorpay payment ID
     * @param signature Signature from frontend
     * @return true if signature is valid
     */
    public boolean verifyPaymentSignature(String orderId, String paymentId, String signature) {
        logger.info("Verifying payment signature for order: {}, payment: {}", orderId, paymentId);

        try {
            JSONObject attributes = new JSONObject();
            attributes.put("razorpay_order_id", orderId);
            attributes.put("razorpay_payment_id", paymentId);
            attributes.put("razorpay_signature", signature);

            boolean isValid = Utils.verifyPaymentSignature(attributes, 
                razorpayClient.getAuth()[1]); // Get secret from auth
            
            logger.info("Payment signature verification result: {}", isValid);
            return isValid;
            
        } catch (RazorpayException e) {
            logger.error("Payment signature verification failed", e);
            return false;
        }
    }

    /**
     * Verify webhook signature.
     * 
     * Razorpay sends webhook with X-Razorpay-Signature header.
     * Signature = HMAC-SHA256(request_body, webhook_secret)
     * 
     * @param payload Raw request body
     * @param signature X-Razorpay-Signature header value
     * @return true if signature is valid
     */
    public boolean verifyWebhookSignature(String payload, String signature) {
        logger.info("Verifying webhook signature");

        try {
            String generatedSignature = hmacSha256(payload, webhookSecret);
            boolean isValid = generatedSignature.equals(signature);
            
            logger.info("Webhook signature verification result: {}", isValid);
            return isValid;
            
        } catch (Exception e) {
            logger.error("Webhook signature verification failed", e);
            return false;
        }
    }

    /**
     * Generate HMAC-SHA256 signature.
     */
    private String hmacSha256(String data, String secret) throws Exception {
        Mac mac = Mac.getInstance("HmacSHA256");
        SecretKeySpec secretKey = new SecretKeySpec(
            secret.getBytes(StandardCharsets.UTF_8), 
            "HmacSHA256"
        );
        mac.init(secretKey);
        
        byte[] hash = mac.doFinal(data.getBytes(StandardCharsets.UTF_8));
        return bytesToHex(hash);
    }

    /**
     * Convert bytes to hex string.
     */
    private String bytesToHex(byte[] bytes) {
        Formatter formatter = new Formatter();
        for (byte b : bytes) {
            formatter.format("%02x", b);
        }
        String result = formatter.toString();
        formatter.close();
        return result;
    }
}
